### ISSUE TITLE
Oracle 12c Impl failure

### ISSUE THREAD

**Issue by ryantaplin** [RyanTaplin1705/docker-write-servlet#10]
Impl Oracle 12c to try run editioned scripts in app as per bug #4 

Getting following error:
```java.sql.SQLException: ORA-28040: No matching authentication protocol```

Need to look into this error; a little bit of research says something about some setting that needs changing. Unsure of how to do that at the moment on the docker instance.

**Comment by RyanTaplin1705** [comment]
Investigate use of c3p0

https://www.programcreek.com/java-api-examples/index.php?api=com.mchange.v2.c3p0.ComboPooledDataSource

**Comment by RyanTaplin1705** [comment]
I fixed this error by execing into docker image and adding the .ora file with the line specified in some guides. I can now connect to the database successfully but none of my statements are working.

I am always receiving empty result set back and my executeQueries are not updating my database.

**Comment by RyanTaplin1705** [comment]
A little bit baffled. The values entered via the app seem to appear on the page output. The other values entered manually via SQLDeveloper won't appear though. 

@hanfak or @tjheslin any ideas? :sob: 

```
database.update(String.format("INSERT INTO %s (staff_id, title, firstname, surname) VALUES\n" +
                "(99, 'Mr', 'Abba', 'Booboo')", TABLE_NAME, order.title, order.firstname, order.surname));
```
![screenshot from 2017-08-22 22-42-26](https://user-images.githubusercontent.com/11903234/29588972-613b3a5a-878b-11e7-9f0b-d660fc7541a6.png)

![screenshot from 2017-08-22 22-44-05](https://user-images.githubusercontent.com/11903234/29588987-6f1f8572-878b-11e7-8cbe-78900323a389.png)

**Comment by RyanTaplin1705** [comment]
Doesn't even update an existing value on the output. Seems as if the application is accessing/ viewing a child table and all the values are filtering through to the table we see on SQLDeveloper however not back the other way.

![screenshot from 2017-08-22 22-52-39](https://user-images.githubusercontent.com/11903234/29589313-bd59d6c4-878c-11e7-81fc-88dbd67bb2e3.png)

**Comment by RyanTaplin1705** [comment]
I brain farted. I didn't commit my changes in SQL developer. I'm really surprised it doesn't conflict?
